init:
	git clone https://dihur.si/si-ius/cpz.git
	git clone https://dihur.si/si-ius/odz.git
	git clone https://dihur.si/si-ius/slovenskipravnik1917.git
	git clone https://dihur.si/si-ius/slovenskipravnik1920.git
	git clone https://dihur.si/si-ius/ustvol.git
	git clone https://dihur.si/si-ius/zkp1890.git
	git clone https://dihur.si/si-ius/zkp1929.git
update:
	cd cpz/; git pull origin
	cd odz/; git pull origin
	cd slovenskipravnik1917/; git pull origin
	cd slovenskipravnik1920/; git pull origin
	cd ustvol/; git pull origin
	cd zkp1890/; git pull origin
	cd zkp1929/; git pull origin
