get:
	cd cpz/; git pull origin
	cd odz/; git pull origin
	cd slovenskipravnik1917/; git pull origin
	cd slovenskipravnik1920/; git pull origin
	cd ustvol/; git pull origin
	cd zkp1890/; git pull origin
	cd zkp1929/; git pull origin

